server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # For Angular router
  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    # Create proxy to backend through Docker DNS
    proxy_pass http://backend:8080/;

    # Send the actual host
    proxy_set_header Host $host;

    # Send the actual IP
    proxy_set_header X-Real-IP $remote_addr;
  }
}
