name: logistics-platform-staging

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8000:80"
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env.staging
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "9090:9090"
    networks:
      - app-network

  db:
    container_name: mariadb-staging
    image: mariadb:11.4
    restart: unless-stopped
    env_file:
      - .env.staging
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -u root -p$MARIADB_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-network

  minio:
    container_name: minio-staging
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    env_file:
      - .env.staging
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
  minio_data:
