name: logistics-platform-dev

services:
  db:
    container_name: mariadb-dev
    image: mariadb:11.4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -u root -p$MARIADB_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-network

  minio:
    container_name: minio-dev
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
  minio_data:
