spring:
  config:
    activate:
      on-profile: dev

  jwt:
    expiration-ms: 86400000 # 24h

  flyway:
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.manosgrigorakis.logisticsplatform: DEBUG

swagger:
  enabled: true