spring:
  application:
    name: logistics-platform

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}

app:
  reset_password:
    expires: ${TOKEN_EXPIRES_IN}