-- Encrypt Password for Initial Setup: https://www.bcryptcalculator.com/
-- INSERT INTO users(role_id, first_name, last_name, email, password, phone, status, enabled, created_at)
-- VALUES
--     (1, '<first-name>', '<last-name>', '<email>', '<password>', NULL, 'ACTIVE',1,  NOW());