import { provideIcons, provideNgIconsConfig } from '@ng-icons/core';
import {
  lucideAlertTriangle,
  lucideBriefcaseBusiness,
  lucideBuilding,
  lucideBuilding2,
  lucideCalendar,
  lucideCheckCircle2,
  lucideChevronDown,
  lucideCog,
  lucideDownload,
  lucideEye,
  lucideFile,
  lucideFileBox,
  lucideFileCheck,
  lucideFileText,
  lucideFileXCorner,
  lucideFilter,
  lucideInfo,
  lucideLogOut,
  lucideMail,
  lucidePhone,
  lucidePieChart,
  lucidePlus,
  lucideReceiptEuro,
  lucideRefreshCcw,
  lucideScale,
  lucideSearch,
  lucideTrash,
  lucideTruck,
  lucideUpload,
  lucideUser,
  lucideUserCircle,
  lucideUserCog,
  lucideUsers,
  lucideX,
} from '@ng-icons/lucide';

export const appIconsConfig = provideNgIconsConfig({
  size: '1.5rem',
  color: 'currentColor',
});

export const appIconsProvider = provideIcons({
  lucideTruck,
  lucideUsers,
  lucideUserCog,
  lucidePieChart,
  lucideBuilding,
  lucideUserCircle,
  lucideCog,
  lucideLogOut,
  lucideSearch,
  lucideFilter,
  lucideChevronDown,
  lucideRefreshCcw,
  lucidePlus,
  lucideTrash,
  lucideInfo,
  lucideAlertTriangle,
  lucideX,
  lucideUser,
  lucideMail,
  lucidePhone,
  lucideCalendar,
  lucideFileText,
  lucideDownload,
  lucideFileBox,
  lucideEye,
  lucideScale,
  lucideUpload,
  lucideCheckCircle2,
  lucideFileCheck,
  lucideBuilding2,
  lucideReceiptEuro,
  lucideFile,
  lucideFileXCorner,
  lucideBriefcaseBusiness,
});
